homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 34.803640
  longitude: -86.687480
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 236
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

http:
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/ha-htpc.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/ha-htpc.duckdns.org/privkey.pem
  base_url: ha-htpc.duckdns.org
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Insert Panels
panel_iframe:
  nodered:
    title: 'Node-Red'
    url: 'https://ha-htpc.duckdns.org:1880'
    icon: mdi:nodejs

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

sensor:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/ha-htpc.duckdns.org/cert.pem | awk '{ print $NF }'"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Groups
group: !include groups.yaml

# Automations
# automation: !include automations.yaml

automation:
  - alias: 'Auto Renew SSL Cert'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
    action:
      service: shell_command.renew_ssl

# Scripts
script: !include scripts.yaml

shell_command:
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

# Add-ons

# Blink Cameras
blink:
  username: !secret blink_un
  password: !secret blink_pw

# Nest
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

# LIFX
light:
  - platform: lifx

# iOS
ios:
